[tools]
"cargo:searchfox-cli" = "latest"
"cargo:treeherder-cli" = "latest"
node = "22"
"npm:web-ext" = "latest"
"pipx:MozPhab" = "latest"
"pipx:mozregression" = "latest"
python = "3.11"
uv = "latest"

[settings]
env_file = ".env"

[env]
BUILD_PLATFORM = "{{os()}}"
_.path = [
  "{{config_root}}/bin",
  "{{env.HOME}}/.mozbuild/git-cinnabar",
  "{{env.HOME}}/.mozbuild/sccache",
]
_.source = { path = "{{config_root}}/bin/buildenv", tools = true }

[shell_alias]
workspace = "source $BUILD_BASE/bin/workspace"
build_app = "$BUILD_BASE/bin/set_env BUILD_APP"
build_channel = "$BUILD_BASE/bin/set_env BUILD_CHANNEL"
build_level = "$BUILD_BASE/bin/set_env BUILD_LEVEL"
build_target = "$BUILD_BASE/bin/set_env BUILD_TARGET"
build_type = "$BUILD_BASE/bin/set_env BUILD_TYPE"
